{
   "before_install" : "true",
   "env" : {
      "global" : {
         "secure" : "jWr2UuEwIAQwsPCWoJWphF7J70y\u002ByypMOdqGEwJHPZYCtDvO5rkWamt32LcikfOZYDv3jA3Qp1p9yuntUeWGsdA/N4kVeQsW7tt92xTTxl6WoTLqNN2c9CjOAHpMDwGfRRihwFXCiiE2kc5TMxyGCwsNDAZs6H/fxYgNzpr33gs="
      }
   },
   "git" : {
      "submodules" : false
   },
   "install" : "make test-deps",
   "jobs" : {
      "include" : [
         {
            "before_install" : "true",
            "install" : "true",
            "script" : "curl -f https://gist.githubusercontent.com/wakaba/ab553f86cd017e0cb28c6dbb5364b009/raw/travis-merge-job.pl | perl",
            "stage" : "merge"
         }
      ]
   },
   "language" : "perl",
   "perl" : [
      "5.26",
      "5.14",
      "5.12"
   ],
   "script" : "make test"
}
