{
   "jobs" : {
      "build" : {
         "environment" : {
            "CIRCLE_ARTIFACTS" : "/tmp/circle-artifacts/build"
         },
         "machine" : {
            "image" : "ubuntu-2004:202008-01"
         },
         "steps" : [
            "checkout",
            {
               "run" : {
                  "command" : "mkdir -p $CIRCLE_ARTIFACTS"
               }
            },
            {
               "store_artifacts" : {
                  "path" : "/tmp/circle-artifacts/build"
               }
            }
         ]
      },
      "gaa4" : {
         "machine" : {
            "image" : "ubuntu-2004:202008-01"
         },
         "steps" : [
            "checkout",
            {
               "run" : {
                  "command" : "git config --global user.email \u0022temp@circleci.test\u0022;git config --global user.name \u0022CircleCI\u0022"
               }
            },
            {
               "run" : {
                  "command" : "make deps"
               }
            },
            {
               "run" : {
                  "command" : "make updatenightly"
               }
            },
            {
               "deploy" : {
                  "command" : "git commit -m auto"
               }
            },
            {
               "deploy" : {
                  "command" : "git push origin \u002B`git rev-parse HEAD`:refs/heads/nightly"
               }
            }
         ]
      }
   },
   "version" : 2,
   "workflows" : {
      "build" : {
         "jobs" : [
            "build"
         ]
      },
      "gaa4" : {
         "jobs" : [
            "gaa4"
         ],
         "triggers" : [
            {
               "schedule" : {
                  "cron" : "56 13 * * *",
                  "filters" : {
                     "branches" : {
                        "only" : [
                           "staging"
                        ]
                     }
                  }
               }
            }
         ]
      },
      "version" : 2
   }
}
